# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Brice Thomas
tagline:             'dev, code, nlp and stuff.'
description:         'Software engineering, architecture and Natural Language Processing enthusiast • In love with creative code and creative project • Developer at <a href="http://iadvize.com" target="_blank">iAdvize</a> in Nantes, France <br/> <div class="follow"><a href="https://twitter.com/Cowaa" target="_blank"><i class="fa fa-twitter"></i></a><a class="follow" href="https://github.com/Cowa" target="_blank"><i class="fa fa-github"></i></a></div>'
url:                 http://cowa.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Brice Thomas
  url:               https://twitter.com/Cowaa

# Custom vars
version:             1.0.0
